version: '3'
services:
  
  omniNames:
    build:
      context: ./2_omniorb
      dockerfile: Dockerfile
      args:
        rhrepo: "http://172.17.0.1/yum/redhawk/"
    image: redhawk-compose:omniserver 
    restart: always
    network_mode: "bridge"
    ports:
      - 2809:2809
    privileged: true
    entrypoint:
      - /omniNames.sh
  
  omniEvents:
    image: redhawk-compose:omniserver
    restart: always
    links:
      - omniNames
    network_mode: "bridge"
    ports:
      - 11169:11169
    privileged: true
    entrypoint:
      - /omniEvents.sh

  domain:
    build:
      context: ./3_domain
      dockerfile: Dockerfile
    image: redhawk-compose:domain
    restart: always
    links:
      - omniNames
      - omniEvents
    network_mode: "bridge"
    entrypoint:
      - /startDomain.sh
