version: '3'
services:
  repo:
    image: redhawk-compose:repo
    network_mode: bridge
    ports:
      - "80:80"

  omniNames:
    image: redhawk-compose:omniserver
    restart: always
    environment:
      - nameserver=localhost
      - eventserver=localhost
    network_mode: "bridge"
    ports:
      - 2809:2809
    command:
      - /usr/local/bin/omniNames.sh

  omniEvents:
    image: redhawk-compose:omniserver
    restart: always
    links:
      - omniNames
    environment:
      - nameserver=omniNames
      - eventserver=localhost
    network_mode: "bridge"
    ports:
      - 11169:11169
    command:
      - /usr/local/bin/omniEvents.sh

  domain:
    image: redhawk-compose:domain
    restart: always
    links:
      - omniNames
      - omniEvents
    environment:
      - nameserver=omniNames
      - eventserver=omniEvents
      - domainname=REDHAWK_COMPOSE
    network_mode: "bridge"
    command:
      - /usr/local/bin/startDomain.sh

  gpp:
    image: redhawk-compose:gpp
    depends_on: ['domain']
    restart: always
    links:
      - omniNames
      - omniEvents
    environment:
      - nameserver=omniNames
      - eventserver=omniEvents
      - domainname=REDHAWK_COMPOSE
    network_mode: "bridge"
    command:
      - /usr/local/bin/startGPP.sh

  ide:
    image: redhawk-compose:ide
    depends_on: ['domain']
    links:
      - omniNames
      - omniEvents
    environment:
      - nameserver=omniNames
      - eventserver=omniEvents
      - DISPLAY=$DISPLAY
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    network_mode: "bridge"
    command:
      - /usr/bin/rhide
