version: '3'
services:
  
  base:
    build:
      context: ./base
      dockerfile: Dockerfile
      args:
        rhrepo: ${rhrepo:-"http://$$host:8080/yum/redhawk/"}
    image: redhawk-compose:base

  omniserver:
    build:
      context: ./omniorb
      dockerfile: Dockerfile
    depends_on:
      - base
    image: redhawk-compose:omniserver

  domain:
    build:
      context: ./domain
      dockerfile: Dockerfile
    depends_on:
      - omniserver
    image: redhawk-compose:domain

  gpp:
    build:
      context: ./gpp
      dockerfile: Dockerfile
    depends_on:
      - domain
    image: redhawk-compose:gpp

  ide:
    build:
      context: ./ide
      dockerfile: Dockerfile
    depends_on:
      - domain
    image: redhawk-compose:ide
